version: "3.8"
services:
  front:
    build: ./frontend
    container_name: frontend
    networks:
    -  mynet
    # ports:
    #   - 3000:3000
    volumes:
      - ./frontend:/frontend
      - /frontend/node_modules
    environment:
      - REACT_APP_BACKEND_URL=api
  back:
    build: ./backend
    container_name: backend
    networks:
      - mynet
    # ports:
    #   - 5000:4000
    volumes:
      - ./backend:/backend
      - /backend/node_modules
    environment: 
      - MYSQL_URL=db
      - MYSQL_USER=appuser
      - MYSQL_PASSWORD=testdb
      - MYSQL_DB=comsecure
  db:
    image: mysql:5.7
    restart: always
    container_name: db
    volumes:
      - ./db:/db
      - ./db/db_data:/var/lib/mysql
    command: --init-file /db/init.sql
    environment:
      MySQL_ROOT_PASSWORD: P@sswordIsNu11
      MYSQL_ALLOW_EMPTY_PASSWORD: 'true'
      MYSQL_PASSWORD: testdb
      MYSQL_DB: comsecure
    expose:
      - "3306"
    networks:
      - mynet
  nginx:
    image: nginx
    volumes:
      - ./frontend/nginx/nginx.conf:/etc/nginx/conf.d/nginx.conf:ro
    ports:
      - 8000:8000
    depends_on:
      - front
      - back
    networks:
      - mynet
networks:
  mynet:

