version: "3.8"
services:
  front:
    build: ./frontend
    container_name: frontend
    networks:
      - mynet
    ports:
      - 4000:3000
  back:
    build: ./backend
    container_name: backend
    networks:
      - mynet
    ports:
      - 5000:5000
  db:
    image: mysql:5.7
    restart: always
    container_name: db
    volumes:
      - ./db:/db
      - ./db/db_data:/var/lib/mysql
    command: --init-file /db/init.sql
    environment:
      MySQL_ROOT_PASSWORD: root
      MYSQL_ALLOW_EMPTY_PASSWORD: 'true'
      MYSQL_PASSWORD: testdb
      MYSQL_DB: comsecure
    expose:
      - "3306"
    networks:
      - mynet
networks:
  mynet: {}
