version: "3.8"
services:
 front:
  build: ./frontend
  container_name: frontend
  networks:
   - mynet
  ports:
   - 4000:3000
 back:
  build: ./backend
  container_name: backend
  networks:
   - mynet
  ports:
   - 5000:5000
db:
   image: "mysql:latest"
   restart: always
   command: '--init-file /data/application/init.sql'
   volumes:
    - /backend/init.sql:/data/application/init.sql
   expose:
    - "3306"
   environment:
    MYSQL_PASSWORD: /run/secrets/mysql_pw
    MYSQL_DATABASE: /run/secrets/mysql_db
   secrets:
    - mysql_pw
    - mysql_db
   networks:
    - mynet
networks:
 mynet: {}
secrets:
 mysql_pw:
  file:
 mysql_db:
  file:
